version: '3'
services:
  database:
    image: "postgres:alpine" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"

volumes:
  database-data: # named volumes can be managed easier using docker-compose

#  rd-professional-db:
#    build:
#      context: database
#    image: hmcts/rd-professional-db
#    container_name: rd-professional-db
#    volumes:
#      - rd-professional-db-volume:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-dbrefdata}"
#    ports:
#      - 5428:5432
