version: '3'
services:
  database:
    image: jamesocog/postgres:alpine # use latest official postgres version
    network_mode: bridge
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
  demproject:
    build:
      context: database
    image: developmenttask
    network_mode: bridge
    container_name: workCogproject
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - database
    links:
      - database
volumes:
  database-data: # named volumes can be managed easier using docker-compose